version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Monta tu directorio actual en '/code' dentro del contenedor
      - .:/code
    ports:
      - "8081:8081"
    # Usa el archivo .env para cargar las variables de entorno en el contenedor
    env_file:
      - .env
    command: python run.py
