version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=development
    command: python run.py
