version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8081
    env_file:
      - .env
    ports:
      - "8081:8081"
    command: ["hupper", "-m", "flask", "run"]
