class Answer:
    def __init__(self, data):
        self._id = data.get('_id')
        self.answer_date = data.get('answer_date')
        self.area_id = data.get('area_id', None)
        self.attribute_id = data.get('attribute_id')
        self.attribute_importance = data.get('attribute_importance', None)
        self.check_description = data.get('check_description', None)
        self.check_items = data.get('check_items', None)
        self.contract_id = data.get('contract_id', None)
        self.custom_field = data.get('custom_field', None)
        self.description = data.get('description', None)
        self.employee_id = data.get('employee_id')
        self.geographic_area_id = data.get('geographic_area_id', None)
        self.invoked_employee_id = data.get('invoked_employee_id', None)
        self.manager_id = data.get('manager_id', None)
        self.professional_category_id = data.get('professional_category_id', None)
        self.question_id = data.get('question_id')
        self.salary_id = data.get('salary_id', None)
        self.score = data.get('score')
        self.source = data.get('source', None)
        self.study_id = data.get('study_id', None)
        self.way_order = data.get('way_order', None)
        self.weight = data.get('weight', None)
        self.working_time_id = data.get('working_time_id', None)

